<a href="https://colab.research.google.com/github/domonjo01/colaboratory/blob/master/my_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a = 3
b = 2
print ( a + b )

5


In [ ]:
a = True; b = False
print(a+b)

1


In [ ]:
a = 3; b = 5

c = a + b ; print(c)

d = a < b; print(d)

e = 3 < 4 and 4 < 5; print(e)

8
True
True


In [ ]:
a = [1, 2, 3, 4, 5]

b = a[3] ; print(b)

a.append(6) ; print(a)

a[2] = 99 ; print(a)

4
[1, 2, 3, 4, 5, 6]
[1, 2, 99, 4, 5, 6]


In [ ]:
a = (1, 2, 3, 4, 5)

b = a[2]
print(b)

3


In [ ]:
(2,)

(2,)

In [ ]:
a = [1, 2, 3]
a1, a2, a3 = a ; print(a1, a2, a3)

b = (4, 5, 6) # タプル
b1, b2, b3 = b ; print(b1, b2, b3)

1 2 3
4 5 6


In [ ]:
a = {"Artificial":1, "Intelligence":2} # 辞書の作成
print(a["Artificial"]) # "Artificial"のキーを持つ値を取得

a["Intelligence"] = 7
print(a)

a["ML"] = 3 ; print(a)

1
{'Artificial': 1, 'Intelligence': 7}
{'Artificial': 1, 'Intelligence': 7, 'ML': 3}


In [ ]:
a = [1, 1, 2, 3, 4, 4, 5, 5, 5]
print(a)

b = set(a)
print(b)

b.add(6) ; print(b)

b.remove(3) ; print(b)

[1, 1, 2, 3, 4, 4, 5, 5, 5]
{1, 2, 3, 4, 5}
{1, 2, 3, 4, 5, 6}
{1, 2, 4, 5, 6}


In [ ]:
a = 3 ; b = 2 ; print ( a + b )

5


In [ ]:
a = 13
if a < 12:
  print("Good morning!")
elif a < 17:
  print("Good afternoon!")
elif a < 21:
  print("Good evening!")
else:
  print("Good night!")

Good afternoon!


In [ ]:
for a in [3, 5, 9, 17]:
  print(a)

for a in range(5):
  print(a)

3
5
9
17
0
1
2
3
4


In [ ]:
a = 0
while a < 3:
  print(a)
  a += 1

0
1
2


In [ ]:
a = [1, 2, 3, 4, 5, 6, 7]
b = [c*2+1 for c in a]
print(b)

[3, 5, 7, 9, 11, 13, 15]


In [ ]:
def add(a, b): # 関数の定義
  c = a + b
  return c

print(add(2, 3)) # 関数の実行

5


In [ ]:
def add(a, b=4):
  c = a + b
  return c

print(add(3))

7


In [ ]:
def add(a, b, c):
  d = a + b + c
  print(d)

e = (2, 4, 6)
add(*e)

12


In [ ]:
a = 21

def showNumbers():
  b = 43
  print(a, b)

showNumbers()

21 43


In [ ]:
a = 21

def setLocalNumber():
  a = 43
  print("Local:", a)

setLocalNumber()
print("Global:", a)

Local: 43
Global: 21


In [ ]:
a = 21

def setGlobalNumber():
  global a
  a = 43
  print("Global:", a)

setGlobalNumber()
print("Global:", a)

Global: 43
Global: 43


In [ ]:
class Calc: # Clacがクラス名
  def __init__(self, a):
    self.a = a

  def add(self, b):
    print(self.a + b)

  def multiply(self, b):
    print(self.a * b)

9
16


In [ ]:
calc = Calc(1)
calc.add(5)
calc.multiply(4)

6
4


In [ ]:
class ClacNext(Calc):  # Calcを継承
  def subtract(self, b):
    print(self.a - b)

  def divide(self, b):
    print(self.a / b)


calc_next = ClacNext(4) # インスタンスcalc_nextを生成
calc_next.add(5) # 継承元のメソッド
calc_next.multiply(5) # 継承元のメソッド
calc_next.subtract(5)
calc_next.divide(5)

9
20
-1
0.8


In [ ]:
class Calc: # Clacクラス
  def __init__(self, a): # __init__()メソッド
    self.a = a

  def __call__(self, c): # __call__()メソッド
    print(self.a * c + c)

  def add(self, b): # add()メソッド
    print(self.a + b)

  def multiply(self, b): #m multiply()メソッド
    print(self.a * b )

cl = Calc(3) # インスタンスclを作成

# インスタンス名clを使って__call__()メソッドを呼ぶ
cl(5)

20


In [ ]:
greetings = "Good morning!\nGood afternoon!\nGood evening!\nGood night!"

with open("greetings.txt", "w") as f:
  f.write(greetings)

In [ ]:
with open("greetings.txt", "r") as f:
  print(f.read())

Good morning!
Good afternoon!
Good evening!
Good night!


In [ ]:
from google.colab import files

uploaded = files.upload()
for key in uploaded.keys():
  print(uploaded[key].decode("utf-8"))

Saving test.txt to test.txt
test


In [ ]:
files.download("greetings.txt")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
from google.colab import drive

drive.mount('/content/drive/')

Mounted at /content/drive/


In [ ]:
import os

path = '/content/drive/My Drive/greetings/'

if not os.path.exists(path):
  os.makedirs(path)

with open('/content/drive/My Drive/greetings/hello.txt', 'w') as f:
  f.write("Hello!")

In [1]:
import numpy as np

# PythonのリストからNumPyの配列を作る
a = np.array(([0, 1, 2, 3, 4, 5])) # aが配列
print(a)

[0 1 2 3 4 5]


In [2]:
import numpy as np

b = np.array([[0, 1, 2], [3, 4, 5]]) # 2重のリストからNumPyの2次元配列を作る
print(b)

[[0 1 2]
 [3 4 5]]


In [3]:
import numpy as np

c = np.array([[[0, 1, 2], [1, 2, 3]], [[2, 3, 4], [3, 4, 5]]]) # 3重のリストからNumPyの3次元配列を作る
print(c)

[[[0 1 2]
  [1 2 3]]

 [[2 3 4]
  [3 4 5]]]


In [6]:
import numpy as np

a = np.array([[0, 1, 2], [3, 4, 5]]) # 2次元配列

print(a)
print()

print(a + 2)
print()

print(a * 2)

[[0 1 2]
 [3 4 5]]

[[2 3 4]
 [5 6 7]]

[[ 0  2  4]
 [ 6  8 10]]
